apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: kpack.community.tanzu.vmware.com.0.5.0
spec:
  refName: kpack.community.tanzu.vmware.com
  version: 0.5.0
  releaseNotes: "https://github.com/pivotal/kpack/releases/tag/v0.5.0"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/buildservice/kpack/bundle@sha256:e1ecc2c6ac35c3e13d0a1e3617c477eee18fa1cbf1ccae17b3343ad31e6870e9
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
