apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.12.0
directories:
- path: config/upstream
  contents:
    - path: .
      imgpkgBundle:
        image: projects.registry.vmware.com/buildservice/kpack/bundle@sha256:c521ab952b8b8dcfc3c305b089b0be2b422b62d7101a9f6f741eba582bdeffc4
      newRootPath: config
- path: .imgpkg
  contents:
    - path: .
      imgpkgBundle:
        image: projects.registry.vmware.com/buildservice/kpack/bundle@sha256:c521ab952b8b8dcfc3c305b089b0be2b422b62d7101a9f6f741eba582bdeffc4
      newRootPath: .imgpkg
